export type ProviderUsageSectionLabels = {
  primary: string;
  secondary?: string;
  tertiary?: string;
};

export type ProviderIconFallback =
  | "AppWindow"
  | "ArrowRightCircle"
  | "BarChart"
  | "Bolt"
  | "Box"
  | "Bubble"
  | "Cloud"
  | "Code"
  | "Globe"
  | "Microphone"
  | "Network"
  | "Person"
  | "SpeakerOn"
  | "Stars"
  | "Terminal"
  | "TwoPeople";

export type ProviderCatalogEntry = {
  name: string;
  iconSlug: string;
  iconFallback?: ProviderIconFallback;
  brandColor: string;
  usageSectionLabels: ProviderUsageSectionLabels;
  dashboardUrl?: string;
  subscriptionDashboardUrl?: string;
  statusPageUrl?: string;
};

export const PROVIDER_CATALOG = {
  codex: {
    name: "Codex",
    iconSlug: "codex",
    iconFallback: "Terminal",
    brandColor: "#49A3B0",
    usageSectionLabels: { primary: "Session", secondary: "Weekly" },
    dashboardUrl: "https://chatgpt.com/codex/settings/usage",
    statusPageUrl: "https://status.openai.com/",
  },
  claude: {
    name: "Claude",
    iconSlug: "claude",
    iconFallback: "Bubble",
    brandColor: "#CC7C5E",
    usageSectionLabels: { primary: "Session", secondary: "Weekly", tertiary: "Sonnet" },
    dashboardUrl: "https://console.anthropic.com/settings/billing",
    subscriptionDashboardUrl: "https://claude.ai/settings/usage",
    statusPageUrl: "https://status.claude.com/",
  },
  clinepass: {
    name: "ClinePass",
    iconSlug: "clinepass",
    iconFallback: "Code",
    brandColor: "#61A3FA",
    usageSectionLabels: { primary: "5-hour", secondary: "Weekly", tertiary: "Monthly" },
    dashboardUrl: "https://app.cline.bot/dashboard/subscription?personal=true",
  },
  cursor: {
    name: "Cursor",
    iconSlug: "cursor",
    iconFallback: "ArrowRightCircle",
    brandColor: "#00BFA5",
    usageSectionLabels: { primary: "Total", secondary: "Cursor", tertiary: "Third Party" },
    dashboardUrl: "https://cursor.com/dashboard?tab=usage",
    statusPageUrl: "https://status.cursor.com",
  },
  opencode: {
    name: "OpenCode",
    iconSlug: "opencode",
    iconFallback: "Code",
    brandColor: "#3B82F6",
    usageSectionLabels: { primary: "5-hour", secondary: "Weekly" },
    dashboardUrl: "https://opencode.ai/auth",
  },
  opencodego: {
    name: "OpenCode Go",
    iconSlug: "opencodego",
    iconFallback: "Code",
    brandColor: "#3B82F6",
    usageSectionLabels: { primary: "5-hour", secondary: "Weekly", tertiary: "Monthly" },
    dashboardUrl: "https://opencode.ai/auth",
  },
  alibaba: {
    name: "Alibaba",
    iconSlug: "alibaba",
    brandColor: "#FF6A00",
    usageSectionLabels: { primary: "5-hour", secondary: "Weekly", tertiary: "Monthly" },
    dashboardUrl: "https://modelstudio.console.alibabacloud.com/ap-southeast-1/?tab=coding-plan#/efm/coding_plan",
    statusPageUrl: "https://status.aliyun.com",
  },
  factory: {
    name: "Droid",
    iconSlug: "factory",
    brandColor: "#FF6B35",
    usageSectionLabels: { primary: "Standard", secondary: "Premium" },
    dashboardUrl: "https://app.factory.ai/settings/billing",
    statusPageUrl: "https://status.factory.ai",
  },
  fireworks: {
    name: "Fireworks",
    iconSlug: "fireworks",
    iconFallback: "Bolt",
    brandColor: "#F25B1C",
    usageSectionLabels: { primary: "Spend", secondary: "Spend" },
    dashboardUrl: "https://app.fireworks.ai",
  },
  gemini: {
    name: "Gemini",
    iconSlug: "gemini",
    iconFallback: "Bolt",
    brandColor: "#AB87EA",
    usageSectionLabels: { primary: "Pro", secondary: "Flash", tertiary: "Flash Lite" },
    dashboardUrl: "https://gemini.google.com",
    statusPageUrl: "https://www.google.com/appsstatus/dashboard/products/npdyhgECDJ6tB66MxXyo/history",
  },
  antigravity: {
    name: "Antigravity",
    iconSlug: "antigravity",
    brandColor: "#60BA7E",
    usageSectionLabels: { primary: "Gemini Models", secondary: "Claude and GPT" },
    statusPageUrl: "https://www.google.com/appsstatus/dashboard/products/npdyhgECDJ6tB66MxXyo/history",
  },
  copilot: {
    name: "Copilot",
    iconSlug: "copilot",
    iconFallback: "Person",
    brandColor: "#A855F7",
    usageSectionLabels: { primary: "Premium", secondary: "Chat" },
    dashboardUrl: "https://github.com/settings/copilot",
    statusPageUrl: "https://www.githubstatus.com/",
  },
  zai: {
    name: "z.ai / GLM",
    iconSlug: "zai",
    iconFallback: "Globe",
    brandColor: "#E85A6A",
    usageSectionLabels: { primary: "5-hour", secondary: "Weekly" },
    dashboardUrl: "https://z.ai/manage-apikey/coding-plan/personal/my-plan",
  },
  minimax: {
    name: "MiniMax",
    iconSlug: "minimax",
    brandColor: "#FE603C",
    usageSectionLabels: { primary: "Prompts", secondary: "Window" },
    dashboardUrl: "https://platform.minimax.io/user-center/payment/coding-plan?cycle_type=3",
  },
  kimi: {
    name: "Kimi Code",
    iconSlug: "kimi",
    brandColor: "#FE603C",
    usageSectionLabels: { primary: "7-day usage", secondary: "5-hour usage" },
    dashboardUrl: "https://www.kimi.com/code/console",
  },
  kilo: {
    name: "Kilo",
    iconSlug: "kilo",
    iconFallback: "BarChart",
    brandColor: "#F27027",
    usageSectionLabels: { primary: "Credits", secondary: "Kilo Pass" },
    dashboardUrl: "https://app.kilo.ai/usage",
  },
  kiro: {
    name: "Kiro",
    iconSlug: "kiro",
    brandColor: "#FF9900",
    usageSectionLabels: { primary: "Credits", secondary: "Bonus" },
    dashboardUrl: "https://app.kiro.dev/account/usage",
    statusPageUrl: "https://health.aws.amazon.com/health/status",
  },
  vertexai: {
    name: "Vertex AI",
    iconSlug: "vertexai",
    iconFallback: "Globe",
    brandColor: "#4285F4",
    usageSectionLabels: { primary: "Requests", secondary: "Tokens" },
    dashboardUrl: "https://console.cloud.google.com/vertex-ai",
    statusPageUrl: "https://status.cloud.google.com",
  },
  augment: {
    name: "Augment",
    iconSlug: "augment",
    iconFallback: "Bolt",
    brandColor: "#6366F1",
    usageSectionLabels: { primary: "Credits", secondary: "Usage" },
    dashboardUrl: "https://app.augmentcode.com/account/subscription",
    statusPageUrl: "https://status.augmentcode.com",
  },
  jetbrains: {
    name: "JetBrains AI",
    iconSlug: "jetbrains",
    iconFallback: "AppWindow",
    brandColor: "#FF3399",
    usageSectionLabels: { primary: "Current", secondary: "Refill" },
  },
  amp: {
    name: "Amp",
    iconSlug: "amp",
    iconFallback: "Bolt",
    brandColor: "#DC2626",
    usageSectionLabels: { primary: "Amp Free", secondary: "Balance" },
    dashboardUrl: "https://ampcode.com/settings/usage",
  },
  ollama: {
    name: "Ollama",
    iconSlug: "ollama",
    iconFallback: "Box",
    brandColor: "#888888",
    usageSectionLabels: { primary: "Session", secondary: "Weekly" },
    dashboardUrl: "https://ollama.com/settings",
  },
  synthetic: {
    name: "Synthetic",
    iconSlug: "synthetic",
    brandColor: "#141414",
    usageSectionLabels: { primary: "Five-hour quota", secondary: "Weekly tokens", tertiary: "Search hourly" },
  },
  warp: {
    name: "Warp",
    iconSlug: "warp",
    iconFallback: "ArrowRightCircle",
    brandColor: "#938BB4",
    usageSectionLabels: { primary: "Credits", secondary: "Add-on credits" },
    dashboardUrl: "https://docs.warp.dev/reference/cli/api-keys",
  },
  openrouter: {
    name: "OpenRouter",
    iconSlug: "openrouter",
    iconFallback: "TwoPeople",
    brandColor: "#6467F2",
    usageSectionLabels: { primary: "Credits", secondary: "Usage" },
    dashboardUrl: "https://openrouter.ai/settings/credits",
    statusPageUrl: "https://status.openrouter.ai",
  },
  perplexity: {
    name: "Perplexity",
    iconSlug: "perplexity",
    iconFallback: "Globe",
    brandColor: "#20B2AA",
    usageSectionLabels: { primary: "Credits", secondary: "Bonus credits", tertiary: "Purchased" },
    dashboardUrl: "https://www.perplexity.ai/account/usage",
    statusPageUrl: "https://status.perplexity.com/",
  },
  openai: {
    name: "OpenAI",
    iconSlug: "codex",
    iconFallback: "Terminal",
    brandColor: "#0F826E",
    usageSectionLabels: { primary: "Spend", secondary: "Requests" },
    dashboardUrl: "https://platform.openai.com/usage",
    statusPageUrl: "https://status.openai.com",
  },
  azureopenai: {
    name: "Azure OpenAI",
    iconSlug: "codex",
    iconFallback: "Terminal",
    brandColor: "#0078D4",
    usageSectionLabels: { primary: "Status", secondary: "Deployment" },
    dashboardUrl: "https://ai.azure.com",
    statusPageUrl: "https://azure.status.microsoft/en-us/status",
  },
  alibabatokenplan: {
    name: "Alibaba Token Plan",
    iconSlug: "alibaba",
    brandColor: "#FF6A00",
    usageSectionLabels: { primary: "Credits", secondary: "Usage" },
    dashboardUrl: "https://bailian.console.aliyun.com/cn-beijing?tab=plan#/efm/subscription/token-plan",
    statusPageUrl: "https://status.aliyun.com",
  },
  qwencloud: {
    name: "Qwen Cloud",
    iconSlug: "qwencloud",
    iconFallback: "Globe",
    brandColor: "#615CED",
    usageSectionLabels: { primary: "5-hour", secondary: "Weekly" },
    dashboardUrl: "https://home.qwencloud.com/billing/subscription/token-plan-individual",
    statusPageUrl: "https://status.alibabacloud.com",
  },
  manus: {
    name: "Manus",
    iconSlug: "manus",
    brandColor: "#34322D",
    usageSectionLabels: { primary: "Monthly credits", secondary: "Daily refresh" },
    dashboardUrl: "https://manus.im",
  },
  moonshot: {
    name: "Moonshot / Kimi Open Platform",
    iconSlug: "kimi",
    brandColor: "#205DEB",
    usageSectionLabels: { primary: "Balance", secondary: "Balance" },
    dashboardUrl: "https://platform.moonshot.ai/console/account",
  },
  t3chat: {
    name: "T3 Chat",
    iconSlug: "t3chat",
    iconFallback: "Bubble",
    brandColor: "#F56647",
    usageSectionLabels: { primary: "Base", secondary: "Overage" },
    dashboardUrl: "https://t3.chat/settings/customization",
    subscriptionDashboardUrl: "https://t3.chat/settings/subscription",
  },
  elevenlabs: {
    name: "ElevenLabs",
    iconSlug: "elevenlabs",
    iconFallback: "SpeakerOn",
    brandColor: "#EBEBE6",
    usageSectionLabels: { primary: "Credits", secondary: "Voices" },
    dashboardUrl: "https://elevenlabs.io/app/developers/usage",
    subscriptionDashboardUrl: "https://elevenlabs.io/app/subscription",
    statusPageUrl: "https://status.elevenlabs.io",
  },
  windsurf: {
    name: "Windsurf",
    iconSlug: "windsurf",
    iconFallback: "Code",
    brandColor: "#34E8BB",
    usageSectionLabels: { primary: "Daily", secondary: "Weekly" },
    dashboardUrl: "https://windsurf.com/subscription/usage",
  },
  mimo: {
    name: "Xiaomi MiMo",
    iconSlug: "mimo",
    brandColor: "#FF6900",
    usageSectionLabels: { primary: "Credits", secondary: "Window" },
    dashboardUrl: "https://platform.xiaomimimo.com/#/console/balance",
  },
  doubao: {
    name: "Doubao",
    iconSlug: "doubao",
    brandColor: "#3370FF",
    usageSectionLabels: { primary: "5-hour", secondary: "Weekly", tertiary: "Monthly" },
    dashboardUrl:
      "https://console.volcengine.com/ark/region:ark+cn-beijing/openManagement?LLM=%7B%7D&advancedActiveKey=subscribe",
  },
  abacus: {
    name: "Abacus AI",
    iconSlug: "abacus",
    iconFallback: "BarChart",
    brandColor: "#38BDF8",
    usageSectionLabels: { primary: "Credits", secondary: "Weekly" },
    dashboardUrl: "https://apps.abacus.ai/chatllm/admin/compute-points-usage",
  },
  mistral: {
    name: "Mistral",
    iconSlug: "mistral",
    iconFallback: "Bolt",
    brandColor: "#FF500F",
    usageSectionLabels: { primary: "Balance" },
    dashboardUrl: "https://admin.mistral.ai/organization/usage",
    statusPageUrl: "https://status.mistral.ai",
  },
  deepseek: {
    name: "DeepSeek",
    iconSlug: "deepseek",
    brandColor: "#527DF0",
    usageSectionLabels: { primary: "Balance", secondary: "Balance" },
    dashboardUrl: "https://platform.deepseek.com/usage",
    statusPageUrl: "https://status.deepseek.com",
  },
  deepinfra: {
    name: "DeepInfra",
    iconSlug: "deepinfra",
    iconFallback: "Cloud",
    brandColor: "#2A3275",
    usageSectionLabels: { primary: "Balance", secondary: "Balance" },
    dashboardUrl: "https://deepinfra.com/dash",
    statusPageUrl: "https://status.deepinfra.com",
  },
  codebuff: {
    name: "Codebuff",
    iconSlug: "codebuff",
    iconFallback: "Code",
    brandColor: "#44FF00",
    usageSectionLabels: { primary: "Credits", secondary: "Weekly" },
    dashboardUrl: "https://www.codebuff.com/usage",
  },
  crof: {
    name: "Crof",
    iconSlug: "crof",
    brandColor: "#2EAB94",
    usageSectionLabels: { primary: "Credits", secondary: "Credits" },
    dashboardUrl: "https://crof.ai/dashboard",
  },
  venice: {
    name: "Venice",
    iconSlug: "venice",
    iconFallback: "Globe",
    brandColor: "#3399FF",
    usageSectionLabels: { primary: "Balance", secondary: "Balance" },
    dashboardUrl: "https://venice.ai/settings/api",
  },
  commandcode: {
    name: "Command Code",
    iconSlug: "commandcode",
    iconFallback: "Terminal",
    brandColor: "#A04DFD",
    usageSectionLabels: { primary: "5-hour", secondary: "Weekly", tertiary: "Monthly" },
    dashboardUrl: "https://commandcode.ai/studio",
    subscriptionDashboardUrl: "https://commandcode.ai/settings/billing",
  },
  stepfun: {
    name: "StepFun",
    iconSlug: "stepfun",
    brandColor: "#2196F2",
    usageSectionLabels: { primary: "5h Window", secondary: "Weekly Window" },
    dashboardUrl: "https://platform.stepfun.com/plan-usage",
  },
  bedrock: {
    name: "AWS Bedrock",
    iconSlug: "bedrock",
    iconFallback: "Cloud",
    brandColor: "#FF9900",
    usageSectionLabels: { primary: "Budget", secondary: "Cost" },
    dashboardUrl: "https://console.aws.amazon.com/bedrock",
    statusPageUrl: "https://health.aws.amazon.com/health/status",
  },
  grok: {
    name: "Grok",
    iconSlug: "grok",
    iconFallback: "Stars",
    brandColor: "#10A37F",
    usageSectionLabels: { primary: "Credits", secondary: "On-demand" },
    dashboardUrl: "https://grok.com/?_s=usage",
    statusPageUrl: "https://status.x.ai",
  },
  groq: {
    name: "Groq",
    iconSlug: "groq",
    iconFallback: "Bolt",
    brandColor: "#F56844",
    usageSectionLabels: { primary: "Requests", secondary: "Tokens" },
    dashboardUrl: "https://console.groq.com/dashboard/usage",
    statusPageUrl: "https://status.groq.com",
  },
  llmproxy: {
    name: "LLM Proxy",
    iconSlug: "llmproxy",
    iconFallback: "Network",
    brandColor: "#24B47E",
    usageSectionLabels: { primary: "Quota", secondary: "Requests" },
  },
  deepgram: {
    name: "Deepgram",
    iconSlug: "deepgram",
    iconFallback: "Microphone",
    brandColor: "#6467F2",
    usageSectionLabels: { primary: "Requests", secondary: "Usage" },
    dashboardUrl: "https://console.deepgram.com/project/",
    statusPageUrl: "https://status.deepgram.com",
  },
  devin: {
    name: "Devin",
    iconSlug: "devin",
    iconFallback: "Code",
    brandColor: "#46B482",
    usageSectionLabels: { primary: "Daily", secondary: "Weekly" },
    dashboardUrl: "https://app.devin.ai",
    subscriptionDashboardUrl: "https://app.devin.ai/settings/usage",
  },
  zed: {
    name: "Zed",
    iconSlug: "zed",
    iconFallback: "AppWindow",
    brandColor: "#084EFF",
    usageSectionLabels: { primary: "Edit predictions", secondary: "Billing cycle" },
  },
  sakana: {
    name: "Sakana AI",
    iconSlug: "sakana",
    brandColor: "#2975DB",
    usageSectionLabels: { primary: "5-hour", secondary: "Weekly" },
    dashboardUrl: "https://console.sakana.ai/billing",
  },
  qoder: {
    name: "Qoder",
    iconSlug: "qoder",
    iconFallback: "Code",
    brandColor: "#10B981",
    usageSectionLabels: { primary: "Credits", secondary: "Balance" },
    dashboardUrl: "https://qoder.com/account/usage",
  },
  litellm: {
    name: "LiteLLM",
    iconSlug: "litellm",
    iconFallback: "Network",
    brandColor: "#4C89F0",
    usageSectionLabels: { primary: "Personal budget", secondary: "Team budget" },
  },
  poe: {
    name: "Poe",
    iconSlug: "poe",
    iconFallback: "Bubble",
    brandColor: "#5D5CDE",
    usageSectionLabels: { primary: "Points", secondary: "Points" },
    dashboardUrl: "https://poe.com/api/keys",
  },
  chutes: {
    name: "Chutes",
    iconSlug: "chutes",
    iconFallback: "Bolt",
    brandColor: "#3184FF",
    usageSectionLabels: { primary: "4-hour quota", secondary: "Monthly quota" },
    dashboardUrl: "https://chutes.ai",
  },
  neuralwatt: {
    name: "Neuralwatt",
    iconSlug: "neuralwatt",
    iconFallback: "Bolt",
    brandColor: "#38D98C",
    usageSectionLabels: { primary: "Subscription", secondary: "Key allowance" },
    dashboardUrl: "https://portal.neuralwatt.com/dashboard",
    subscriptionDashboardUrl: "https://portal.neuralwatt.com/dashboard",
  },
  clawrouter: {
    name: "ClawRouter",
    iconSlug: "clawrouter",
    iconFallback: "Network",
    brandColor: "#596EF6",
    usageSectionLabels: { primary: "Monthly budget", secondary: "Requests" },
    dashboardUrl: "https://clawrouter.openclaw.ai/dashboard/access",
  },
  wayfinder: {
    name: "Wayfinder",
    iconSlug: "wayfinder",
    iconFallback: "Globe",
    brandColor: "#10A37F",
    usageSectionLabels: { primary: "Savings", secondary: "Requests" },
    // Default gateway dashboard (WayfinderSettingsReader.dashboardURL with empty env).
    dashboardUrl: "http://127.0.0.1:8088/router",
  },
  longcat: {
    name: "LongCat",
    iconSlug: "longcat",
    iconFallback: "Bubble",
    brandColor: "#FFD100",
    usageSectionLabels: { primary: "Quota", secondary: "Fuel Pack" },
    dashboardUrl: "https://longcat.chat/platform/",
  },
  sub2api: {
    name: "sub2api",
    iconSlug: "sub2api",
    iconFallback: "Network",
    brandColor: "#2DC6D8",
    usageSectionLabels: { primary: "Quota", secondary: "Weekly quota", tertiary: "Monthly quota" },
  },
  zenmux: {
    name: "ZenMux",
    iconSlug: "zenmux",
    iconFallback: "Network",
    brandColor: "#6C5CE7",
    usageSectionLabels: { primary: "5-hour quota", secondary: "Weekly quota" },
    dashboardUrl: "https://zenmux.ai/platform/management",
  },
  aiand: {
    name: "ai&",
    iconSlug: "aiand",
    iconFallback: "BarChart",
    brandColor: "#E25C2B",
    usageSectionLabels: { primary: "Spend", secondary: "Spend" },
    dashboardUrl: "https://console.aiand.com",
  },
  zoommate: {
    name: "ZoomMate",
    iconSlug: "zoommate",
    iconFallback: "TwoPeople",
    brandColor: "#0B5CFF",
    usageSectionLabels: { primary: "Credits", secondary: "Credits" },
    dashboardUrl: "https://zoommate.zoom.us/#/?settings=credit-usage",
    statusPageUrl: "https://www.zoomstatus.com/",
  },
  xai: {
    name: "xAI",
    iconSlug: "xai",
    iconFallback: "Stars",
    brandColor: "#8E8E93",
    usageSectionLabels: { primary: "Spend", secondary: "Spend" },
    dashboardUrl: "https://console.x.ai",
    statusPageUrl: "https://status.x.ai",
  },
  notion: {
    name: "Notion AI",
    iconSlug: "notion",
    iconFallback: "AppWindow",
    brandColor: "#337EA9",
    usageSectionLabels: { primary: "Rolling", secondary: "Monthly" },
    dashboardUrl: "https://app.notion.com/",
    statusPageUrl: "https://status.notion.so/",
  },
  ibmbob: {
    name: "IBM Bob",
    iconSlug: "ibmbob",
    iconFallback: "Terminal",
    brandColor: "#0E61FA",
    usageSectionLabels: { primary: "Monthly Bobcoins", secondary: "Monthly Bobcoins" },
    dashboardUrl: "https://bob.ibm.com",
    subscriptionDashboardUrl: "https://bob.ibm.com",
    statusPageUrl: "https://status.bob.ibm.com",
  },
} satisfies Record<string, ProviderCatalogEntry>;

export const PROVIDER_ID_ALIASES: Record<string, string> = {
  "alibaba-coding-plan": "alibaba",
  bailian: "alibaba",
  "alibaba-token-plan": "alibabatokenplan",
  "alibaba-token": "alibabatokenplan",
  "bailian-token-plan": "alibabatokenplan",
  "qwen-cloud": "qwencloud",
  qwen: "qwencloud",
  "qwen-token-plan": "qwencloud",
  "azure-openai": "azureopenai",
  aoai: "azureopenai",
  "openai-api": "openai",
  abacusai: "abacus",
  "abacus-ai": "abacus",
  groqcloud: "groq",
  "groq-api": "groq",
  "aws-bedrock": "bedrock",
  manicode: "codebuff",
  "command-code": "commandcode",
  crofai: "crof",
  dg: "deepgram",
  "deep-seek": "deepseek",
  ds: "deepseek",
  "deep-infra": "deepinfra",
  di: "deepinfra",
  volcengine: "doubao",
  ark: "doubao",
  bytedance: "doubao",
  "11labs": "elevenlabs",
  eleven: "elevenlabs",
  fw: "fireworks",
  "llm-api-key-proxy": "llmproxy",
  "llm-proxy": "llmproxy",
  "xiaomi-mimo": "mimo",
  "mini-max": "minimax",
  "mistral-ai": "mistral",
  "step-fun": "stepfun",
  sf: "stepfun",
  "t3-chat": "t3chat",
  t3: "t3chat",
  ven: "venice",
  "sakana-ai": "sakana",
  "litellm-proxy": "litellm",
  "chutes.ai": "chutes",
  "claw-router": "clawrouter",
  "wayfinder-router": "wayfinder",
  "kilo-ai": "kilo",
  "kimi-ai": "kimi",
  "warp-ai": "warp",
  "warp-terminal": "warp",
  "synthetic.new": "synthetic",
  or: "openrouter",
  "z.ai": "zai",
  nw: "neuralwatt",
  neural: "neuralwatt",
  "long-cat": "longcat",
  lc: "longcat",
  "sub-2-api": "sub2api",
  "zen-mux": "zenmux",
  "ai&": "aiand",
  "ai-and": "aiand",
  "notion-ai": "notion",
  notionai: "notion",
  "ibm-bob": "ibmbob",
  bob: "ibmbob",
  bobshell: "ibmbob",
};
